from join.exceptions import JoinException


class SlithIRError(JoinException):
    pass
