class JoinException(Exception):
    pass


class JoinError(JoinException):
    pass
